---
dependencies: []

galaxy_info:
  standalone: true
  role_name: foldersetup
  author: "Antonio Turner"
  description: "Deploy folder boilerplate for project"

  license: "license (BSD, MIT)"
  min_ansible_version: "2.10"
  platforms:
    - name: Fedora
      versions:
        - all
    - name: Ubuntu
      versions:
        - all
    - name: Debian
      versions:
        - all
  galaxy_tags:
    - networking
    - system
    - web
    - certbot
    - letsencrypt
    - encryption
    - certificates
    - ssl
    - https
